### ISSUE TITLE
gWASM: subtasks details in history

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/golem-electron#586]
## Rationale
At the moment only a short task summary is shown for gWASM on tasks history. GUI should show subtasks details. In particular we want to show how VbR is working.

### Functional specification
No big functional change. Only tasks history is affected. 
On the list there are Blender and gWASM tasks. You can expand a Blender task and see subtasks. Furthermore, you can expand a subtask and see jobs. We would like to have the same functionality for gWASM tasks.

### User Interface
![g2](https://user-images.githubusercontent.com/29129196/64272597-fe6daa80-cf3f-11e9-8b2b-ca3bf16e3cea.png)
<img width="487" alt="g3" src="https://user-images.githubusercontent.com/29129196/64272627-0cbbc680-cf40-11e9-9c4b-d2f6b90707ad.png">

## Dependencies
I hope it is just a matter of displaying and there will be no change in RPC.

### Development
* [ ] Feature implemented
* [ ] Feature unit/integration tests implemented

### Dev QA
* [ ] Basic tests by the developer pass
* [ ] Unit tests pass
* [ ] Golem integration tests pass
* [ ] Concent integration tests pass
* [ ] Concent acceptance tests pass

**Please choose the priority label for QA. It is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

### QA team
* [ ] Base scenario passes
* [ ] Additional test 1 passes... 
* [ ] ... 

## Issues encountered during QA
_When adding an issue here, please update testing scenarios and QA progress above_
* [ ] link to issue... 
* [ ] ...

**Comment by lukasz-glen** [comment]
This is not for 0.21 release.
