### ISSUE TITLE
Developer mode GUI - subtask details 

### ISSUE THREAD

**Issue by badb** [golemfactory/golem-electron#85]
Add possibility to display subtask details in GUI. There should be information about:

- [x] stdout log (can be file path)
- [x] stderr log (can be file path)
- [x] ip of the node that has computed the subtask 
- [x] name of the node that has computed the subtask
- [x] short subtask description
- [x] time of computation

**Comment by mdtanrikulu** [comment]
In PR #93.
